file_length:
  warning: 600
  error: 1200
  ignore_comment_only_lines: true
  
file_types_order:
  order:
    - supporting_type
    - main_type
    - extension
    - preview_provider

closure_body_length:
  - 30 # warning
  - 60 # error

function_body_length:
  - 60 # warning
  - 120 # error
  
identifier_name:
  min_length:
    error: 3
  excluded:
    - id

line_length:
  - 120 # warning

type_body_length:
  - 300 # warning
  - 400 # error
  
type_contents_order:
  order:
    - type_alias
    - associated_type
    - case
    - ib_outlet
    - ib_inspectable
    - subtype
    - type_property
    - instance_property
    - initializer
    - deinitializer
    - view_life_cycle_method
    - type_method
    - other_method
    - ib_action
    - subscript
  
type_name:
  min_length: 3
  max_length: 100

opt_in_rules:
  - anyobject_protocol
  - array_init
  - attributes
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - identical_operands
  - implicitly_unwrapped_optional
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_space_in_method_call
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - static_operator
  - strict_fileprivate
  - test_case_accessibility
  - toggle_bool
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

reporter: "xcode"

allow_zero_lintable_files: true

excluded:
    - Dangerfile.swift
